<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model),
);

$this->menu=array(
	array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->id)),
	array('label'=>Yii::t('app', 'Back to') . ' ' . $model->label(2), 'url'=>array('admin')),	
	//array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	//array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	//array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->id)),
	//array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm'=>'Are you sure you want to delete this item?')),
	//array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>
<h3></h3>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data' => $model,
	'attributes' => array(
'id',
'Emp_ID',
'Emp_Name',
'Position',
'Department',
'Schedule',
'Emp_Status',
'Monthly_Basic',
'Semi_Monthly_Basic',
'Tax_Status',
'Monthly_Night_Diff',
'Total_Semi_Monthly',
'Days_Work',
'Late_Absent',
'Extra_Allowance',
'New_Salary_with_ND',
'Total_Days_Work',
'Per_Day',
'Per_Hr',
'Regular_Pay',
'Total_Night_Diff',
'ND_Per_Days',
'Total_Days_with_ND',
'Total_ND',
'Total_Gross_Pay',
'Total_Basic_Salary',
'SSS',
'Emp_Share_SSS',
'EC',
'PHIC',
'Emp_Share_PHIC',
'HDMF',
'Emp_Share_HDMF',
'Total_HDMF',
'Total_Tax_Income',
'Withholding_Tax',
'SSS_Loan',
'HDMF_Loan',
'Insurance',
'Rental_Housing',
'Total_Deduction',
'Non_PTO_Hrs',
'Non_PTO_Amt',
'Net_Pay',
'Payroll_Period',
'Payroll_Date',
'Payroll_Date_Words',
'Total_Earnings',
'Overtime_hrs',
'Overtime',
'Regular_OT',
'NDOT',
'Spec_Holiday',
'Spec_OT',
'Spec_NDOT',
'Reg_Holiday',
'RegHoliday_OT',
'RegHoliday_NDOT',
'VL',
'PTO_With_Tax',
'PTO_Wo_Tax',
'Basic_Pay',
'Cash_Out',
'Starting_Salary',
'sumEverything',
'initialYrEnder',
'YearEnder',
'Excess_to_13mo',
'countLang',
'Adjustment',
'Salary_Adjustment',
'Add_to_MB',
'Add_to_ND',
'Add_to_OT',
'Add_to_PTO_With_Tax',
'Add_to_SSS',
'Add_to_PHIC',
'Add_to_HDMF',
'Add_to_Taxable_Income',
'Add_to_NonTaxableDeduct',
'Add_to_Tax_Due',
'Taxable_Adj',
'NonTaxableAdj',
'Act_Status',
'Rate_with_ND',
	),
)); ?>

