<?php

/**
 * This is the model base class for the table "ot_sub_code".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OtSubCode".
 *
 * Columns in table "ot_sub_code" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $ot_code
 * @property string $title
 * @property string $rate
 * @property string $NDrate
 * @property string $AdPercent
 * @property string $description
 *
 */
abstract class BaseOtSubCode extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ot_sub_code';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OtSubCode|OtSubCodes', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('ot_code, title, rate, NDrate, AdPercent', 'required'),
			array('ot_code, rate', 'length', 'max'=>10),
			array('title', 'length', 'max'=>100),
			array('NDrate, AdPercent', 'length', 'max'=>20),
			array('description', 'safe'),
			array('description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('ot_code, title, rate, NDrate, AdPercent, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ot_code' => Yii::t('app', 'Ot Code'),
			'title' => Yii::t('app', 'Title'),
			'rate' => Yii::t('app', 'Rate'),
			'NDrate' => Yii::t('app', 'Ndrate'),
			'AdPercent' => Yii::t('app', 'Ad Percent'),
			'description' => Yii::t('app', 'Description'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ot_code', $this->ot_code, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('rate', $this->rate, true);
		$criteria->compare('NDrate', $this->NDrate, true);
		$criteria->compare('AdPercent', $this->AdPercent, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}