<?php

/**
 * This is the model base class for the table "hris_ot_application".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HrisOtApplicationReport".
 *
 * Columns in table "hris_ot_application" available as properties of the model,
 * followed by relations of table "hris_ot_application" available as properties of the model.
 *
 * @property integer $id
 * @property integer $dept_id
 * @property integer $emp_id
 * @property integer $next_lvl_id
 * @property integer $job_code_id
 * @property string $sub_code_id
 * @property string $in_datetime
 * @property string $out_datetime
 * @property string $reason
 * @property integer $approved_hours
 * @property integer $sup_id
 * @property integer $sup_approve
 * @property string $sup_approve_datetime
 * @property string $sup_disapprove_reason
 * @property integer $mgr_id
 * @property integer $mgr_approve
 * @property string $mgr_approve_datetime
 * @property string $mgr_disapprove_reason
 * @property integer $hr_id
 * @property integer $hr_approve
 * @property string $hr_approve_datetime
 * @property string $hr_disapprove_reason
 * @property integer $employer_id
 * @property integer $employer_approve
 * @property string $employer_approve_datetime
 * @property string $employer_disapprove_reason
 * @property integer $replicated_to_emp_hrs
 * @property string $timestamp
 *
 * @property Employee $employer
 * @property Employee $sup
 * @property Employee $mgr
 * @property Employee $hr
 * @property JobCode $jobCode
 * @property HrisDept $dept
 * @property HrisAccessLvl $nextLvl
 * @property Employee $emp
 * @property HrisOtAttachments[] $hrisOtAttachments
 */
abstract class BaseHrisOtApplicationReport extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'hris_ot_application';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'HrisOtApplicationReport|HrisOtApplicationReports', $n);
	}

	public static function representingColumn() {
		return 'sub_code_id';
	}

	public function rules() {
		return array(
			array('dept_id, emp_id, next_lvl_id, job_code_id, sub_code_id, in_datetime, out_datetime, reason, timestamp', 'required'),
			array('dept_id, emp_id, next_lvl_id, job_code_id, sup_id, sup_approve, mgr_id, mgr_approve, hr_id, hr_approve, employer_id, employer_approve, replicated_to_emp_hrs', 'numerical', 'integerOnly'=>true),
			array('sub_code_id', 'length', 'max'=>10),
			array('sup_approve_datetime, sup_disapprove_reason, mgr_approve_datetime, mgr_disapprove_reason, hr_approve_datetime, hr_disapprove_reason, employer_approve_datetime, employer_disapprove_reason', 'safe'),
			array('approved_hours, sup_id, sup_approve, sup_approve_datetime, sup_disapprove_reason, mgr_id, mgr_approve, mgr_approve_datetime, mgr_disapprove_reason, hr_id, hr_approve, hr_approve_datetime, hr_disapprove_reason, employer_id, employer_approve, employer_approve_datetime, employer_disapprove_reason, replicated_to_emp_hrs', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, dept_id, emp_id, next_lvl_id, job_code_id, sub_code_id, in_datetime, out_datetime, reason, approved_hours, sup_id, sup_approve, sup_approve_datetime, sup_disapprove_reason, mgr_id, mgr_approve, mgr_approve_datetime, mgr_disapprove_reason, hr_id, hr_approve, hr_approve_datetime, hr_disapprove_reason, employer_id, employer_approve, employer_approve_datetime, employer_disapprove_reason, replicated_to_emp_hrs, timestamp', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'employer' => array(self::BELONGS_TO, 'Employee', 'employer_id'),
			'sup' => array(self::BELONGS_TO, 'Employee', 'sup_id'),
			'mgr' => array(self::BELONGS_TO, 'Employee', 'mgr_id'),
			'hr' => array(self::BELONGS_TO, 'Employee', 'hr_id'),
			'jobCode' => array(self::BELONGS_TO, 'JobCode', 'job_code_id'),
			'dept' => array(self::BELONGS_TO, 'HrisDept', 'dept_id'),
			'nextLvl' => array(self::BELONGS_TO, 'HrisAccessLvl', 'next_lvl_id'),
			'emp' => array(self::BELONGS_TO, 'Employee', 'emp_id'),
			'hrisOtAttachments' => array(self::HAS_MANY, 'HrisOtAttachments', 'form_model_id'),
			'subCode' => array(self::BELONGS_TO, 'OtSubCode', 'sub_code_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'dept_id' => null,
			'emp_id' => null,
			'next_lvl_id' => null,
			'job_code_id' => null,
			'sub_code_id' => Yii::t('app', 'Sub Code'),
			'in_datetime' => Yii::t('app', 'In Datetime'),
			'out_datetime' => Yii::t('app', 'Out Datetime'),
			'reason' => Yii::t('app', 'Reason'),
			'approved_hours' => Yii::t('app', 'Approved Hours'),
			'sup_id' => null,
			'sup_approve' => Yii::t('app', 'Sup Approve'),
			'sup_approve_datetime' => Yii::t('app', 'Sup Approve Datetime'),
			'sup_disapprove_reason' => Yii::t('app', 'Sup Disapprove Reason'),
			'mgr_id' => null,
			'mgr_approve' => Yii::t('app', 'Mgr Approve'),
			'mgr_approve_datetime' => Yii::t('app', 'Mgr Approve Datetime'),
			'mgr_disapprove_reason' => Yii::t('app', 'Mgr Disapprove Reason'),
			'hr_id' => null,
			'hr_approve' => Yii::t('app', 'Hr Approve'),
			'hr_approve_datetime' => Yii::t('app', 'Hr Approve Datetime'),
			'hr_disapprove_reason' => Yii::t('app', 'Hr Disapprove Reason'),
			'employer_id' => null,
			'employer_approve' => Yii::t('app', 'Employer Approve'),
			'employer_approve_datetime' => Yii::t('app', 'Employer Approve Datetime'),
			'employer_disapprove_reason' => Yii::t('app', 'Employer Disapprove Reason'),
			'replicated_to_emp_hrs' => Yii::t('app', 'Replicated To Emp Hrs'),
			'timestamp' => Yii::t('app', 'Date Submitted'),
			'employer' => null,
			'sup' => null,
			'mgr' => null,
			'hr' => null,
			'jobCode' => null,
			'dept' => null,
			'nextLvl' => null,
			'emp' => null,
			'hrisOtAttachments' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('dept_id', $this->dept_id);
		$criteria->compare('emp_id', $this->emp_id);
		$criteria->compare('next_lvl_id', $this->next_lvl_id);
		$criteria->compare('job_code_id', $this->job_code_id);
		$criteria->compare('sub_code_id', $this->sub_code_id, true);
		$criteria->compare('in_datetime', $this->in_datetime, true);
		$criteria->compare('out_datetime', $this->out_datetime, true);
		$criteria->compare('reason', $this->reason, true);
		$criteria->compare('approved_hours', $this->approved_hours);
		$criteria->compare('sup_id', $this->sup_id);
		$criteria->compare('sup_approve', $this->sup_approve);
		$criteria->compare('sup_approve_datetime', $this->sup_approve_datetime, true);
		$criteria->compare('sup_disapprove_reason', $this->sup_disapprove_reason, true);
		$criteria->compare('mgr_id', $this->mgr_id);
		$criteria->compare('mgr_approve', $this->mgr_approve);
		$criteria->compare('mgr_approve_datetime', $this->mgr_approve_datetime, true);
		$criteria->compare('mgr_disapprove_reason', $this->mgr_disapprove_reason, true);
		$criteria->compare('hr_id', $this->hr_id);
		$criteria->compare('hr_approve', $this->hr_approve);
		$criteria->compare('hr_approve_datetime', $this->hr_approve_datetime, true);
		$criteria->compare('hr_disapprove_reason', $this->hr_disapprove_reason, true);
		$criteria->compare('employer_id', $this->employer_id);
		$criteria->compare('employer_approve', $this->employer_approve);
		$criteria->compare('employer_approve_datetime', $this->employer_approve_datetime, true);
		$criteria->compare('employer_disapprove_reason', $this->employer_disapprove_reason, true);
		$criteria->compare('replicated_to_emp_hrs', $this->replicated_to_emp_hrs);
		$criteria->compare('timestamp', $this->timestamp, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}