<?php

/**
 * This is the model base class for the table "hris_announcement".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HrisAnnouncement".
 *
 * Columns in table "hris_announcement" available as properties of the model,
 * followed by relations of table "hris_announcement" available as properties of the model.
 *
 * @property integer $id
 * @property integer $emp_id
 * @property string $message
 * @property string $timestamp
 *
 * @property Employee $emp
 */
abstract class BaseHrisAnnouncement extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'hris_announcement';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'HrisAnnouncement|HrisAnnouncements', $n);
	}

	public static function representingColumn() {
		return 'message';
	}

	public function rules() {
		return array(
			array('emp_id, message, timestamp', 'required'),
			array('emp_id', 'numerical', 'integerOnly'=>true),
			array('id, emp_id, message, timestamp', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'emp' => array(self::BELONGS_TO, 'Employee', 'emp_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'emp_id' => null,
			'message' => Yii::t('app', 'Message'),
			'timestamp' => Yii::t('app', 'Timestamp'),
			'emp' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('emp_id', $this->emp_id);
		$criteria->compare('message', $this->message, true);
		$criteria->compare('timestamp', $this->timestamp, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}