<?php

/**
 * This is the model base class for the table "hris_document_category".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HrisDocumentCategory".
 *
 * Columns in table "hris_document_category" available as properties of the model,
 * followed by relations of table "hris_document_category" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 *
 * @property HrisDocument[] $hrisDocuments
 */
abstract class BaseHrisDocumentCategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'hris_document_category';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'HrisDocumentCategory|HrisDocumentCategories', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title', 'required'),
			array('title', 'length', 'max'=>100),
			array('description', 'safe'),
			array('description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'hrisDocuments' => array(self::HAS_MANY, 'HrisDocument', 'category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'hrisDocuments' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}