<?php

/**
 * This is the model base class for the table "hris_mu_application".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HrisMuApplicationReport".
 *
 * Columns in table "hris_mu_application" available as properties of the model,
 * followed by relations of table "hris_mu_application" available as properties of the model.
 *
 * @property integer $id
 * @property integer $emp_id
 * @property integer $dept_id
 * @property integer $job_code_id
 * @property integer $next_lvl_id
 * @property string $clockedin_datetime
 * @property string $clockedout_datetime
 * @property string $hours
 * @property string $from_datetime
 * @property string $to_datetime
 * @property string $reason
 * @property string $remarks
 * @property integer $reliever_id
 * @property integer $reliever_approve
 * @property string $reliever_approve_datetime
 * @property integer $sup_id
 * @property integer $mgr_id
 * @property integer $mgr_approve
 * @property string $mgr_approve_datetime
 * @property string $mgr_disapprove_reason
 * @property integer $sup_approve
 * @property string $sup_approve_datetime
 * @property string $sup_disapprove_reason
 * @property integer $hr_id
 * @property integer $hr_approve
 * @property string $hr_approve_datetime
 * @property string $hr_disapprove_reason
 * @property string $timestamp
 * @property integer $replicated_to_emp_hrs
 *
 * @property JobCode $jobCode
 * @property Employee $emp
 * @property Employee $reliever
 * @property Employee $sup
 * @property Employee $hr
 * @property HrisAccessLvl $nextLvl
 * @property HrisDept $dept
 * @property HrisMuAttachments[] $hrisMuAttachments
 */
abstract class BaseHrisMuApplicationReport extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'hris_mu_application';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'HrisMuApplicationReport|HrisMuApplicationReports', $n);
	}

	public static function representingColumn() {
		return 'clockedin_datetime';
	}

	public function rules() {
		return array(
			array('emp_id, clockedin_datetime, clockedout_datetime, hours, reason, timestamp', 'required'),
			array('emp_id, dept_id, job_code_id, next_lvl_id, reliever_id, reliever_approve, sup_id, mgr_id, mgr_approve, sup_approve, hr_id, hr_approve, replicated_to_emp_hrs', 'numerical', 'integerOnly'=>true),
			array('hours', 'length', 'max'=>3),
			array('from_datetime, to_datetime, remarks, reliever_approve_datetime, mgr_approve_datetime, mgr_disapprove_reason, sup_approve_datetime, sup_disapprove_reason, hr_approve_datetime, hr_disapprove_reason', 'safe'),
			array('dept_id, job_code_id, next_lvl_id, from_datetime, to_datetime, remarks, reliever_id, reliever_approve, reliever_approve_datetime, sup_id, mgr_id, mgr_approve, mgr_approve_datetime, mgr_disapprove_reason, sup_approve, sup_approve_datetime, sup_disapprove_reason, hr_id, hr_approve, hr_approve_datetime, hr_disapprove_reason, replicated_to_emp_hrs', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, emp_id, dept_id, job_code_id, next_lvl_id, clockedin_datetime, clockedout_datetime, hours, from_datetime, to_datetime, reason, remarks, reliever_id, reliever_approve, reliever_approve_datetime, sup_id, mgr_id, mgr_approve, mgr_approve_datetime, mgr_disapprove_reason, sup_approve, sup_approve_datetime, sup_disapprove_reason, hr_id, hr_approve, hr_approve_datetime, hr_disapprove_reason, timestamp, replicated_to_emp_hrs', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'jobCode' => array(self::BELONGS_TO, 'JobCode', 'job_code_id'),
			'emp' => array(self::BELONGS_TO, 'Employee', 'emp_id'),
			'reliever' => array(self::BELONGS_TO, 'Employee', 'reliever_id'),
			'sup' => array(self::BELONGS_TO, 'Employee', 'sup_id'),
			'hr' => array(self::BELONGS_TO, 'Employee', 'hr_id'),
			'nextLvl' => array(self::BELONGS_TO, 'HrisAccessLvl', 'next_lvl_id'),
			'dept' => array(self::BELONGS_TO, 'HrisDept', 'dept_id'),
			'hrisMuAttachments' => array(self::HAS_MANY, 'HrisMuAttachments', 'mu_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'emp_id' => null,
			'dept_id' => null,
			'job_code_id' => null,
			'next_lvl_id' => null,
			'clockedin_datetime' => Yii::t('app', 'Clockedin Datetime'),
			'clockedout_datetime' => Yii::t('app', 'Clockedout Datetime'),
			'hours' => Yii::t('app', 'Hours'),
			'from_datetime' => Yii::t('app', 'From Datetime'),
			'to_datetime' => Yii::t('app', 'To Datetime'),
			'reason' => Yii::t('app', 'Reason'),
			'remarks' => Yii::t('app', 'Remarks'),
			'reliever_id' => null,
			'reliever_approve' => Yii::t('app', 'Reliever Approve'),
			'reliever_approve_datetime' => Yii::t('app', 'Reliever Approve Datetime'),
			'sup_id' => null,
			'mgr_id' => Yii::t('app', 'Mgr'),
			'mgr_approve' => Yii::t('app', 'Mgr Approve'),
			'mgr_approve_datetime' => Yii::t('app', 'Mgr Approve Datetime'),
			'mgr_disapprove_reason' => Yii::t('app', 'Mgr Disapprove Reason'),
			'sup_approve' => Yii::t('app', 'Sup Approve'),
			'sup_approve_datetime' => Yii::t('app', 'Sup Approve Datetime'),
			'sup_disapprove_reason' => Yii::t('app', 'Sup Disapprove Reason'),
			'hr_id' => null,
			'hr_approve' => Yii::t('app', 'Hr Approve'),
			'hr_approve_datetime' => Yii::t('app', 'Hr Approve Datetime'),
			'hr_disapprove_reason' => Yii::t('app', 'Hr Disapprove Reason'),
			'timestamp' => Yii::t('app', 'Timestamp'),
			'replicated_to_emp_hrs' => Yii::t('app', 'Replicated To Emp Hrs'),
			'jobCode' => null,
			'emp' => null,
			'reliever' => null,
			'sup' => null,
			'hr' => null,
			'nextLvl' => null,
			'dept' => null,
			'hrisMuAttachments' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('emp_id', $this->emp_id);
		$criteria->compare('dept_id', $this->dept_id);
		$criteria->compare('job_code_id', $this->job_code_id);
		$criteria->compare('next_lvl_id', $this->next_lvl_id);
		$criteria->compare('clockedin_datetime', $this->clockedin_datetime, true);
		$criteria->compare('clockedout_datetime', $this->clockedout_datetime, true);
		$criteria->compare('hours', $this->hours, true);
		$criteria->compare('from_datetime', $this->from_datetime, true);
		$criteria->compare('to_datetime', $this->to_datetime, true);
		$criteria->compare('reason', $this->reason, true);
		$criteria->compare('remarks', $this->remarks, true);
		$criteria->compare('reliever_id', $this->reliever_id);
		$criteria->compare('reliever_approve', $this->reliever_approve);
		$criteria->compare('reliever_approve_datetime', $this->reliever_approve_datetime, true);
		$criteria->compare('sup_id', $this->sup_id);
		$criteria->compare('mgr_id', $this->mgr_id);
		$criteria->compare('mgr_approve', $this->mgr_approve);
		$criteria->compare('mgr_approve_datetime', $this->mgr_approve_datetime, true);
		$criteria->compare('mgr_disapprove_reason', $this->mgr_disapprove_reason, true);
		$criteria->compare('sup_approve', $this->sup_approve);
		$criteria->compare('sup_approve_datetime', $this->sup_approve_datetime, true);
		$criteria->compare('sup_disapprove_reason', $this->sup_disapprove_reason, true);
		$criteria->compare('hr_id', $this->hr_id);
		$criteria->compare('hr_approve', $this->hr_approve);
		$criteria->compare('hr_approve_datetime', $this->hr_approve_datetime, true);
		$criteria->compare('hr_disapprove_reason', $this->hr_disapprove_reason, true);
		$criteria->compare('timestamp', $this->timestamp, true);
		$criteria->compare('replicated_to_emp_hrs', $this->replicated_to_emp_hrs);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}