<?php

/**
 * This is the model base class for the table "hris_dept".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HrisDept".
 *
 * Columns in table "hris_dept" available as properties of the model,
 * followed by relations of table "hris_dept" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $comment
 *
 * @property HrisUsers[] $hrisUsers
 */
abstract class BaseHrisDept extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'hris_dept';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'HrisDept|HrisDepts', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, comment', 'required'),
			array('title', 'length', 'max'=>50),
			array('id, title, comment', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'hrisUsers' => array(self::HAS_MANY, 'HrisUsers', 'dept_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'comment' => Yii::t('app', 'Comment'),
			'hrisUsers' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('comment', $this->comment, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}