<?php

/**
 * This is the model base class for the table "hris_loa_application".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HrisLoaApplication".
 *
 * Columns in table "hris_loa_application" available as properties of the model,
 * followed by relations of table "hris_loa_application" available as properties of the model.
 *
 * @property integer $id
 * @property integer $emp_id
 * @property integer $job_code_id
 * @property string $from_datetime
 * @property string $to_datetime
 * @property string $reason
 * @property string $remarks
 * @property integer $reliever_id
 * @property integer $reliever_approve
 * @property string $reliever_approve_datetime
 * @property integer $sup_id
 * @property integer $sup_approve
 * @property string $sup_approve_datetime
 * @property string $sup_disapprove_reason
 * @property integer $hr_id
 * @property integer $hr_approve
 * @property string $hr_approve_datetime
 * @property string $hr_disapprove_reason
 *
 * @property Employee $emp
 * @property JobCode $jobCode
 * @property Employee $reliever
 * @property Employee $sup
 * @property Employee $hr
 * @property HrisLoaAttachments[] $hrisLoaAttachments
 */
abstract class BaseHrisLoaApplication extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'hris_loa_application';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'HrisLoaApplication|HrisLoaApplications', $n);
	}

	public static function representingColumn() {
		return 'from_datetime';
	}

	public function rules() {
		return array(
			array('emp_id, job_code_id, from_datetime, to_datetime, reason, reliever_id', 'required'),
			array('emp_id, job_code_id, reliever_id, reliever_approve, sup_id, sup_approve, hr_id, hr_approve', 'numerical', 'integerOnly'=>true),
			array('remarks, reliever_approve_datetime, sup_approve_datetime, sup_disapprove_reason, hr_approve_datetime, hr_disapprove_reason', 'safe'),
			array('remarks, reliever_approve, reliever_approve_datetime, sup_id, sup_approve, sup_approve_datetime, sup_disapprove_reason, hr_id, hr_approve, hr_approve_datetime, hr_disapprove_reason', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, emp_id, job_code_id, from_datetime, to_datetime, reason, remarks, reliever_id, reliever_approve, reliever_approve_datetime, sup_id, sup_approve, sup_approve_datetime, sup_disapprove_reason, hr_id, hr_approve, hr_approve_datetime, hr_disapprove_reason', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'emp' => array(self::BELONGS_TO, 'Employee', 'emp_id'),
			'jobCode' => array(self::BELONGS_TO, 'JobCode', 'job_code_id'),
			'reliever' => array(self::BELONGS_TO, 'Employee', 'reliever_id'),
			'sup' => array(self::BELONGS_TO, 'Employee', 'sup_id'),
			'mgr' => array(self::BELONGS_TO, 'Employee', 'mgr_id'),
			'hr' => array(self::BELONGS_TO, 'Employee', 'hr_id'),
			'hrisLoaAttachments' => array(self::HAS_MANY, 'HrisLoaAttachments', 'form_model_id'),
			'nextLvlId' => array(self::BELONGS_TO, 'HrisAccessLvl', 'next_lvl_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'emp_id' => null,
			'job_code_id' => null,
			'from_datetime' => Yii::t('app', 'From Datetime'),
			'to_datetime' => Yii::t('app', 'To Datetime'),
			'reason' => Yii::t('app', 'Reason'),
			'remarks' => Yii::t('app', 'Remarks'),
			'reliever_id' => null,
			'reliever_approve' => Yii::t('app', 'Reliever Approve'),
			'reliever_approve_datetime' => Yii::t('app', 'Reliever Approve Datetime'),
			'sup_id' => null,
			'sup_approve' => Yii::t('app', 'Sup Approve'),
			'sup_approve_datetime' => Yii::t('app', 'Sup Approve Datetime'),
			'sup_disapprove_reason' => Yii::t('app', 'Sup Disapprove Reason'),
			'hr_id' => null,
			'hr_approve' => Yii::t('app', 'Hr Approve'),
			'hr_approve_datetime' => Yii::t('app', 'Hr Approve Datetime'),
			'hr_disapprove_reason' => Yii::t('app', 'Hr Disapprove Reason'),
			'emp' => null,
			'jobCode' => null,
			'reliever' => null,
			'sup' => null,
			'hr' => null,
			'hrisLoaAttachments' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('emp_id', $this->emp_id);
		$criteria->compare('job_code_id', $this->job_code_id);
		$criteria->compare('from_datetime', $this->from_datetime, true);
		$criteria->compare('to_datetime', $this->to_datetime, true);
		$criteria->compare('reason', $this->reason, true);
		$criteria->compare('remarks', $this->remarks, true);
		$criteria->compare('reliever_id', $this->reliever_id);
		$criteria->compare('reliever_approve', $this->reliever_approve);
		$criteria->compare('reliever_approve_datetime', $this->reliever_approve_datetime, true);
		$criteria->compare('sup_id', $this->sup_id);
		$criteria->compare('sup_approve', $this->sup_approve);
		$criteria->compare('sup_approve_datetime', $this->sup_approve_datetime, true);
		$criteria->compare('sup_disapprove_reason', $this->sup_disapprove_reason, true);
		$criteria->compare('hr_id', $this->hr_id);
		$criteria->compare('hr_approve', $this->hr_approve);
		$criteria->compare('hr_approve_datetime', $this->hr_approve_datetime, true);
		$criteria->compare('hr_disapprove_reason', $this->hr_disapprove_reason, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}