<?php

/**
 * This is the model base class for the table "hris_email_queue_for_forms".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HrisEmailQueueForForms".
 *
 * Columns in table "hris_email_queue_for_forms" available as properties of the model,
 * followed by relations of table "hris_email_queue_for_forms" available as properties of the model.
 *
 * @property integer $id
 * @property integer $template_id
 * @property integer $to_group
 * @property integer $to_user
 * @property string $to
 * @property string $subject
 * @property string $content
 * @property string $model_name
 * @property integer $model_id
 * @property integer $sent
 * @property string $sent_timestamp
 * @property string $timestamp
 *
 * @property HrisEmailTemplate $template
 */
abstract class BaseHrisEmailQueueForForms extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'hris_email_queue_for_forms';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'HrisEmailQueueForForms|HrisEmailQueueForForms', $n);
	}

	public static function representingColumn() {
		return 'timestamp';
	}

	public function rules() {
		return array(
			array('timestamp', 'required'),
			array('template_id, to_group, to_user, model_id, sent', 'numerical', 'integerOnly'=>true),
			array('to, model_name', 'length', 'max'=>50),
			array('subject', 'length', 'max'=>100),
			array('content, sent_timestamp', 'safe'),
			array('template_id, to_group, to_user, to, subject, content, model_name, model_id, sent, sent_timestamp', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, template_id, to_group, to_user, to, subject, content, model_name, model_id, sent, sent_timestamp, timestamp', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'template' => array(self::BELONGS_TO, 'HrisEmailTemplate', 'template_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'template_id' => null,
			'to_group' => Yii::t('app', 'To Group'),
			'to_user' => Yii::t('app', 'To User'),
			'to' => Yii::t('app', 'To'),
			'subject' => Yii::t('app', 'Subject'),
			'content' => Yii::t('app', 'Content'),
			'model_name' => Yii::t('app', 'Model Name'),
			'model_id' => Yii::t('app', 'Model'),
			'sent' => Yii::t('app', 'Sent'),
			'sent_timestamp' => Yii::t('app', 'Sent Timestamp'),
			'timestamp' => Yii::t('app', 'Timestamp'),
			'template' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('template_id', $this->template_id);
		$criteria->compare('to_group', $this->to_group);
		$criteria->compare('to_user', $this->to_user);
		$criteria->compare('to', $this->to, true);
		$criteria->compare('subject', $this->subject, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('model_name', $this->model_name, true);
		$criteria->compare('model_id', $this->model_id);
		$criteria->compare('sent', $this->sent);
		$criteria->compare('sent_timestamp', $this->sent_timestamp, true);
		$criteria->compare('timestamp', $this->timestamp, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}