<?php

/**
 * This is the model base class for the table "it_tickets_category".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TicketsCategory".
 *
 * Columns in table "it_tickets_category" available as properties of the model,
 * followed by relations of table "it_tickets_category" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $timestamp
 *
 * @property ItTickets[] $itTickets
 */
abstract class BaseTicketsCategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'it_tickets_category';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TicketsCategory|TicketsCategories', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>512),
			array('timestamp', 'safe'),
			array('timestamp', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, timestamp', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'itTickets' => array(self::HAS_MANY, 'ItTickets', 'category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'timestamp' => Yii::t('app', 'Timestamp'),
			'itTickets' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('timestamp', $this->timestamp, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}