<?php

/**
 * This is the model base class for the table "archive_payroll".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Payroll".
 *
 * Columns in table "archive_payroll" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $Emp_ID
 * @property string $Emp_Name
 * @property string $Position
 * @property string $Department
 * @property string $Schedule
 * @property string $Emp_Status
 * @property string $Monthly_Basic
 * @property string $Semi_Monthly_Basic
 * @property string $Tax_Status
 * @property string $Monthly_Night_Diff
 * @property string $Total_Semi_Monthly
 * @property string $Days_Work
 * @property string $Late_Absent
 * @property double $Extra_Allowance
 * @property string $New_Salary_with_ND
 * @property string $Total_Days_Work
 * @property string $Per_Day
 * @property string $Per_Hr
 * @property string $Regular_Pay
 * @property string $Total_Night_Diff
 * @property string $ND_Per_Days
 * @property string $Total_Days_with_ND
 * @property string $Total_ND
 * @property string $Total_Gross_Pay
 * @property string $Total_Basic_Salary
 * @property string $SSS
 * @property string $Emp_Share_SSS
 * @property string $EC
 * @property string $PHIC
 * @property string $Emp_Share_PHIC
 * @property string $HDMF
 * @property string $Emp_Share_HDMF
 * @property string $Total_HDMF
 * @property string $Total_Tax_Income
 * @property string $Withholding_Tax
 * @property string $SSS_Loan
 * @property string $HDMF_Loan
 * @property string $Insurance
 * @property string $Rental_Housing
 * @property string $Total_Deduction
 * @property string $Non_PTO_Hrs
 * @property string $Non_PTO_Amt
 * @property string $Net_Pay
 * @property string $Payroll_Period
 * @property string $Payroll_Date
 * @property string $Payroll_Date_Words
 * @property string $Total_Earnings
 * @property string $Overtime_hrs
 * @property string $Overtime
 * @property string $Regular_OT
 * @property string $NDOT
 * @property string $Spec_Holiday
 * @property string $Spec_OT
 * @property string $Spec_NDOT
 * @property string $Reg_Holiday
 * @property string $RegHoliday_OT
 * @property string $RegHoliday_NDOT
 * @property string $VL
 * @property string $PTO_With_Tax
 * @property string $PTO_Wo_Tax
 * @property string $Basic_Pay
 * @property string $Cash_Out
 * @property integer $Starting_Salary
 * @property string $sumEverything
 * @property string $initialYrEnder
 * @property string $YearEnder
 * @property string $Excess_to_13mo
 * @property string $countLang
 * @property string $Adjustment
 * @property string $Salary_Adjustment
 * @property string $Add_to_MB
 * @property string $Add_to_ND
 * @property string $Add_to_OT
 * @property string $Add_to_PTO_With_Tax
 * @property string $Add_to_SSS
 * @property string $Add_to_PHIC
 * @property string $Add_to_HDMF
 * @property string $Add_to_Taxable_Income
 * @property string $Add_to_NonTaxableDeduct
 * @property string $Add_to_Tax_Due
 * @property string $Taxable_Adj
 * @property string $NonTaxableAdj
 * @property string $Act_Status
 * @property string $Rate_with_ND
 *
 */
abstract class BasePayroll extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'archive_payroll';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Payroll|Payrolls', $n);
	}

	public static function representingColumn() {
		return 'Emp_Name';
	}

	public function rules() {
		return array(
			array('Emp_ID, Emp_Name, Position, Department, Schedule, Emp_Status, Monthly_Basic, Semi_Monthly_Basic, Tax_Status, Monthly_Night_Diff, Total_Semi_Monthly, Late_Absent, Extra_Allowance, New_Salary_with_ND, Per_Day, Per_Hr, Regular_Pay, Total_Night_Diff, ND_Per_Days, Total_Days_with_ND, Total_ND, Total_Gross_Pay, Total_Basic_Salary, SSS, Emp_Share_SSS, EC, PHIC, Emp_Share_PHIC, HDMF, Emp_Share_HDMF, Total_HDMF, Total_Tax_Income, Withholding_Tax, SSS_Loan, HDMF_Loan, Insurance, Rental_Housing, Total_Deduction, Non_PTO_Hrs, Non_PTO_Amt, Net_Pay, Payroll_Period, Payroll_Date, Payroll_Date_Words, Total_Earnings, Overtime_hrs, Overtime, Regular_OT, NDOT, Spec_Holiday, Spec_OT, Spec_NDOT, Reg_Holiday, RegHoliday_OT, RegHoliday_NDOT, VL, PTO_With_Tax, PTO_Wo_Tax, Basic_Pay, Cash_Out, Starting_Salary, sumEverything, initialYrEnder, YearEnder, Excess_to_13mo, countLang, Adjustment, Salary_Adjustment, Add_to_MB, Add_to_ND, Add_to_OT, Add_to_PTO_With_Tax, Add_to_SSS, Add_to_PHIC, Add_to_HDMF, Add_to_Taxable_Income, Add_to_NonTaxableDeduct, Add_to_Tax_Due, Taxable_Adj, NonTaxableAdj, Act_Status, Rate_with_ND', 'required'),
			array('Emp_ID, Starting_Salary', 'numerical', 'integerOnly'=>true),
			array('Extra_Allowance', 'numerical'),
			array('Emp_Name, Emp_Status, Payroll_Period, Payroll_Date_Words', 'length', 'max'=>60),
			array('Position, Department, Schedule, Tax_Status', 'length', 'max'=>30),
			array('Monthly_Basic, Semi_Monthly_Basic, Monthly_Night_Diff, Total_Semi_Monthly, Days_Work, Late_Absent, New_Salary_with_ND, Total_Days_Work, Per_Day, Per_Hr, Regular_Pay, Total_Night_Diff, ND_Per_Days, Total_Days_with_ND, Total_ND, Total_Gross_Pay, Total_Basic_Salary, SSS, Emp_Share_SSS, EC, PHIC, Emp_Share_PHIC, HDMF, Emp_Share_HDMF, Total_HDMF, Total_Tax_Income, Withholding_Tax, SSS_Loan, HDMF_Loan, Insurance, Rental_Housing, Total_Deduction, Non_PTO_Hrs, Non_PTO_Amt, Net_Pay, Total_Earnings, Overtime_hrs, Overtime, Regular_OT, NDOT, Spec_Holiday, Spec_OT, Spec_NDOT, Reg_Holiday, RegHoliday_OT, RegHoliday_NDOT, VL, PTO_With_Tax, PTO_Wo_Tax, Basic_Pay, Cash_Out, sumEverything, initialYrEnder, YearEnder, Excess_to_13mo, countLang, Adjustment, Salary_Adjustment, Add_to_MB, Add_to_ND, Add_to_OT, Add_to_PTO_With_Tax, Add_to_SSS, Add_to_PHIC, Add_to_HDMF, Add_to_Taxable_Income, Add_to_NonTaxableDeduct, Add_to_Tax_Due, Taxable_Adj, NonTaxableAdj, Rate_with_ND', 'length', 'max'=>20),
			array('Act_Status', 'length', 'max'=>250),
			array('Days_Work, Total_Days_Work', 'default', 'setOnEmpty' => true, 'value' => null),
			array('Emp_ID, Emp_Name, Position, Department, Schedule, Emp_Status, Monthly_Basic, Semi_Monthly_Basic, Tax_Status, Monthly_Night_Diff, Total_Semi_Monthly, Days_Work, Late_Absent, Extra_Allowance, New_Salary_with_ND, Total_Days_Work, Per_Day, Per_Hr, Regular_Pay, Total_Night_Diff, ND_Per_Days, Total_Days_with_ND, Total_ND, Total_Gross_Pay, Total_Basic_Salary, SSS, Emp_Share_SSS, EC, PHIC, Emp_Share_PHIC, HDMF, Emp_Share_HDMF, Total_HDMF, Total_Tax_Income, Withholding_Tax, SSS_Loan, HDMF_Loan, Insurance, Rental_Housing, Total_Deduction, Non_PTO_Hrs, Non_PTO_Amt, Net_Pay, Payroll_Period, Payroll_Date, Payroll_Date_Words, Total_Earnings, Overtime_hrs, Overtime, Regular_OT, NDOT, Spec_Holiday, Spec_OT, Spec_NDOT, Reg_Holiday, RegHoliday_OT, RegHoliday_NDOT, VL, PTO_With_Tax, PTO_Wo_Tax, Basic_Pay, Cash_Out, Starting_Salary, sumEverything, initialYrEnder, YearEnder, Excess_to_13mo, countLang, Adjustment, Salary_Adjustment, Add_to_MB, Add_to_ND, Add_to_OT, Add_to_PTO_With_Tax, Add_to_SSS, Add_to_PHIC, Add_to_HDMF, Add_to_Taxable_Income, Add_to_NonTaxableDeduct, Add_to_Tax_Due, Taxable_Adj, NonTaxableAdj, Act_Status, Rate_with_ND', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'Emp_ID' => Yii::t('app', 'Emp'),
			'Emp_Name' => Yii::t('app', 'Emp Name'),
			'Position' => Yii::t('app', 'Position'),
			'Department' => Yii::t('app', 'Department'),
			'Schedule' => Yii::t('app', 'Schedule'),
			'Emp_Status' => Yii::t('app', 'Emp Status'),
			'Monthly_Basic' => Yii::t('app', 'Monthly Basic'),
			'Semi_Monthly_Basic' => Yii::t('app', 'Semi Monthly Basic'),
			'Tax_Status' => Yii::t('app', 'Tax Status'),
			'Monthly_Night_Diff' => Yii::t('app', 'Monthly Night Diff'),
			'Total_Semi_Monthly' => Yii::t('app', 'Total Semi Monthly'),
			'Days_Work' => Yii::t('app', 'Days Work'),
			'Late_Absent' => Yii::t('app', 'Late Absent'),
			'Extra_Allowance' => Yii::t('app', 'Extra Allowance'),
			'New_Salary_with_ND' => Yii::t('app', 'New Salary With Nd'),
			'Total_Days_Work' => Yii::t('app', 'Total Days Work'),
			'Per_Day' => Yii::t('app', 'Per Day'),
			'Per_Hr' => Yii::t('app', 'Per Hr'),
			'Regular_Pay' => Yii::t('app', 'Regular Pay'),
			'Total_Night_Diff' => Yii::t('app', 'Total Night Diff'),
			'ND_Per_Days' => Yii::t('app', 'Nd Per Days'),
			'Total_Days_with_ND' => Yii::t('app', 'Total Days With Nd'),
			'Total_ND' => Yii::t('app', 'Total Nd'),
			'Total_Gross_Pay' => Yii::t('app', 'Total Gross Pay'),
			'Total_Basic_Salary' => Yii::t('app', 'Total Basic Salary'),
			'SSS' => Yii::t('app', 'Sss'),
			'Emp_Share_SSS' => Yii::t('app', 'Emp Share Sss'),
			'EC' => Yii::t('app', 'Ec'),
			'PHIC' => Yii::t('app', 'Phic'),
			'Emp_Share_PHIC' => Yii::t('app', 'Emp Share Phic'),
			'HDMF' => Yii::t('app', 'Hdmf'),
			'Emp_Share_HDMF' => Yii::t('app', 'Emp Share Hdmf'),
			'Total_HDMF' => Yii::t('app', 'Total Hdmf'),
			'Total_Tax_Income' => Yii::t('app', 'Total Tax Income'),
			'Withholding_Tax' => Yii::t('app', 'Withholding Tax'),
			'SSS_Loan' => Yii::t('app', 'Sss Loan'),
			'HDMF_Loan' => Yii::t('app', 'Hdmf Loan'),
			'Insurance' => Yii::t('app', 'Insurance'),
			'Rental_Housing' => Yii::t('app', 'Rental Housing'),
			'Total_Deduction' => Yii::t('app', 'Total Deduction'),
			'Non_PTO_Hrs' => Yii::t('app', 'Non Pto Hrs'),
			'Non_PTO_Amt' => Yii::t('app', 'Non Pto Amt'),
			'Net_Pay' => Yii::t('app', 'Net Pay'),
			'Payroll_Period' => Yii::t('app', 'Payroll Period'),
			'Payroll_Date' => Yii::t('app', 'Payroll Date'),
			'Payroll_Date_Words' => Yii::t('app', 'Payroll Date Words'),
			'Total_Earnings' => Yii::t('app', 'Total Earnings'),
			'Overtime_hrs' => Yii::t('app', 'Overtime Hrs'),
			'Overtime' => Yii::t('app', 'Overtime'),
			'Regular_OT' => Yii::t('app', 'Regular Ot'),
			'NDOT' => Yii::t('app', 'Ndot'),
			'Spec_Holiday' => Yii::t('app', 'Spec Holiday'),
			'Spec_OT' => Yii::t('app', 'Spec Ot'),
			'Spec_NDOT' => Yii::t('app', 'Spec Ndot'),
			'Reg_Holiday' => Yii::t('app', 'Reg Holiday'),
			'RegHoliday_OT' => Yii::t('app', 'Reg Holiday Ot'),
			'RegHoliday_NDOT' => Yii::t('app', 'Reg Holiday Ndot'),
			'VL' => Yii::t('app', 'Vl'),
			'PTO_With_Tax' => Yii::t('app', 'Pto With Tax'),
			'PTO_Wo_Tax' => Yii::t('app', 'Pto Wo Tax'),
			'Basic_Pay' => Yii::t('app', 'Basic Pay'),
			'Cash_Out' => Yii::t('app', 'Cash Out'),
			'Starting_Salary' => Yii::t('app', 'Starting Salary'),
			'sumEverything' => Yii::t('app', 'Sum Everything'),
			'initialYrEnder' => Yii::t('app', 'Initial Yr Ender'),
			'YearEnder' => Yii::t('app', 'Year Ender'),
			'Excess_to_13mo' => Yii::t('app', 'Excess To 13mo'),
			'countLang' => Yii::t('app', 'Count Lang'),
			'Adjustment' => Yii::t('app', 'Adjustment'),
			'Salary_Adjustment' => Yii::t('app', 'Salary Adjustment'),
			'Add_to_MB' => Yii::t('app', 'Add To Mb'),
			'Add_to_ND' => Yii::t('app', 'Add To Nd'),
			'Add_to_OT' => Yii::t('app', 'Add To Ot'),
			'Add_to_PTO_With_Tax' => Yii::t('app', 'Add To Pto With Tax'),
			'Add_to_SSS' => Yii::t('app', 'Add To Sss'),
			'Add_to_PHIC' => Yii::t('app', 'Add To Phic'),
			'Add_to_HDMF' => Yii::t('app', 'Add To Hdmf'),
			'Add_to_Taxable_Income' => Yii::t('app', 'Add To Taxable Income'),
			'Add_to_NonTaxableDeduct' => Yii::t('app', 'Add To Non Taxable Deduct'),
			'Add_to_Tax_Due' => Yii::t('app', 'Add To Tax Due'),
			'Taxable_Adj' => Yii::t('app', 'Taxable Adj'),
			'NonTaxableAdj' => Yii::t('app', 'Non Taxable Adj'),
			'Act_Status' => Yii::t('app', 'Act Status'),
			'Rate_with_ND' => Yii::t('app', 'Rate With Nd'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('Emp_ID', $this->Emp_ID);
		$criteria->compare('Emp_Name', $this->Emp_Name, true);
		$criteria->compare('Position', $this->Position, true);
		$criteria->compare('Department', $this->Department, true);
		$criteria->compare('Schedule', $this->Schedule, true);
		$criteria->compare('Emp_Status', $this->Emp_Status, true);
		$criteria->compare('Monthly_Basic', $this->Monthly_Basic, true);
		$criteria->compare('Semi_Monthly_Basic', $this->Semi_Monthly_Basic, true);
		$criteria->compare('Tax_Status', $this->Tax_Status, true);
		$criteria->compare('Monthly_Night_Diff', $this->Monthly_Night_Diff, true);
		$criteria->compare('Total_Semi_Monthly', $this->Total_Semi_Monthly, true);
		$criteria->compare('Days_Work', $this->Days_Work, true);
		$criteria->compare('Late_Absent', $this->Late_Absent, true);
		$criteria->compare('Extra_Allowance', $this->Extra_Allowance);
		$criteria->compare('New_Salary_with_ND', $this->New_Salary_with_ND, true);
		$criteria->compare('Total_Days_Work', $this->Total_Days_Work, true);
		$criteria->compare('Per_Day', $this->Per_Day, true);
		$criteria->compare('Per_Hr', $this->Per_Hr, true);
		$criteria->compare('Regular_Pay', $this->Regular_Pay, true);
		$criteria->compare('Total_Night_Diff', $this->Total_Night_Diff, true);
		$criteria->compare('ND_Per_Days', $this->ND_Per_Days, true);
		$criteria->compare('Total_Days_with_ND', $this->Total_Days_with_ND, true);
		$criteria->compare('Total_ND', $this->Total_ND, true);
		$criteria->compare('Total_Gross_Pay', $this->Total_Gross_Pay, true);
		$criteria->compare('Total_Basic_Salary', $this->Total_Basic_Salary, true);
		$criteria->compare('SSS', $this->SSS, true);
		$criteria->compare('Emp_Share_SSS', $this->Emp_Share_SSS, true);
		$criteria->compare('EC', $this->EC, true);
		$criteria->compare('PHIC', $this->PHIC, true);
		$criteria->compare('Emp_Share_PHIC', $this->Emp_Share_PHIC, true);
		$criteria->compare('HDMF', $this->HDMF, true);
		$criteria->compare('Emp_Share_HDMF', $this->Emp_Share_HDMF, true);
		$criteria->compare('Total_HDMF', $this->Total_HDMF, true);
		$criteria->compare('Total_Tax_Income', $this->Total_Tax_Income, true);
		$criteria->compare('Withholding_Tax', $this->Withholding_Tax, true);
		$criteria->compare('SSS_Loan', $this->SSS_Loan, true);
		$criteria->compare('HDMF_Loan', $this->HDMF_Loan, true);
		$criteria->compare('Insurance', $this->Insurance, true);
		$criteria->compare('Rental_Housing', $this->Rental_Housing, true);
		$criteria->compare('Total_Deduction', $this->Total_Deduction, true);
		$criteria->compare('Non_PTO_Hrs', $this->Non_PTO_Hrs, true);
		$criteria->compare('Non_PTO_Amt', $this->Non_PTO_Amt, true);
		$criteria->compare('Net_Pay', $this->Net_Pay, true);
		$criteria->compare('Payroll_Period', $this->Payroll_Period, true);
		$criteria->compare('Payroll_Date', $this->Payroll_Date, true);
		$criteria->compare('Payroll_Date_Words', $this->Payroll_Date_Words, true);
		$criteria->compare('Total_Earnings', $this->Total_Earnings, true);
		$criteria->compare('Overtime_hrs', $this->Overtime_hrs, true);
		$criteria->compare('Overtime', $this->Overtime, true);
		$criteria->compare('Regular_OT', $this->Regular_OT, true);
		$criteria->compare('NDOT', $this->NDOT, true);
		$criteria->compare('Spec_Holiday', $this->Spec_Holiday, true);
		$criteria->compare('Spec_OT', $this->Spec_OT, true);
		$criteria->compare('Spec_NDOT', $this->Spec_NDOT, true);
		$criteria->compare('Reg_Holiday', $this->Reg_Holiday, true);
		$criteria->compare('RegHoliday_OT', $this->RegHoliday_OT, true);
		$criteria->compare('RegHoliday_NDOT', $this->RegHoliday_NDOT, true);
		$criteria->compare('VL', $this->VL, true);
		$criteria->compare('PTO_With_Tax', $this->PTO_With_Tax, true);
		$criteria->compare('PTO_Wo_Tax', $this->PTO_Wo_Tax, true);
		$criteria->compare('Basic_Pay', $this->Basic_Pay, true);
		$criteria->compare('Cash_Out', $this->Cash_Out, true);
		$criteria->compare('Starting_Salary', $this->Starting_Salary);
		$criteria->compare('sumEverything', $this->sumEverything, true);
		$criteria->compare('initialYrEnder', $this->initialYrEnder, true);
		$criteria->compare('YearEnder', $this->YearEnder, true);
		$criteria->compare('Excess_to_13mo', $this->Excess_to_13mo, true);
		$criteria->compare('countLang', $this->countLang, true);
		$criteria->compare('Adjustment', $this->Adjustment, true);
		$criteria->compare('Salary_Adjustment', $this->Salary_Adjustment, true);
		$criteria->compare('Add_to_MB', $this->Add_to_MB, true);
		$criteria->compare('Add_to_ND', $this->Add_to_ND, true);
		$criteria->compare('Add_to_OT', $this->Add_to_OT, true);
		$criteria->compare('Add_to_PTO_With_Tax', $this->Add_to_PTO_With_Tax, true);
		$criteria->compare('Add_to_SSS', $this->Add_to_SSS, true);
		$criteria->compare('Add_to_PHIC', $this->Add_to_PHIC, true);
		$criteria->compare('Add_to_HDMF', $this->Add_to_HDMF, true);
		$criteria->compare('Add_to_Taxable_Income', $this->Add_to_Taxable_Income, true);
		$criteria->compare('Add_to_NonTaxableDeduct', $this->Add_to_NonTaxableDeduct, true);
		$criteria->compare('Add_to_Tax_Due', $this->Add_to_Tax_Due, true);
		$criteria->compare('Taxable_Adj', $this->Taxable_Adj, true);
		$criteria->compare('NonTaxableAdj', $this->NonTaxableAdj, true);
		$criteria->compare('Act_Status', $this->Act_Status, true);
		$criteria->compare('Rate_with_ND', $this->Rate_with_ND, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}